name: Publish releease
on: push

jobs:
  build:
    name: Test npm publish ${{github.head_ref}} ${{github.ref}} ${{github.ref_name}}
    runs-on: windows-latest
    #if: ${{github.event.commits =~ /github:publish|publish:/}}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node_version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
      
      
